### ISSUE TITLE
todo list for version 1.0

### ISSUE THREAD

**Issue by cbz20** [spinachstealer/KhT#3]
#### examples
- [ ] Compute quotients of (2,-3)-pretzel tangle closures (Liam's email "More tangles" from 2019-08-12)
- [ ] Compute cables of the first _n_ knots in the knot table, interpreted as 1-1-tangles (either as a function or by hand)

#### small new features/reliability/user interface
- [x] create tangle class
- [x] implement oriented tangles and compute absolute grading shift automagically
- [ ] Do more testing for BNAlgebra with coefficients over Q.

#### documentation/code readability
- [ ] Add usage examples to the comments
- [ ] generate documentation [(pdoc)](https://pdoc3.github.io/pdoc/)
- [ ] packaging: add requirements file; minimize use of external libraries; check if pdftk is available on all platforms

#### speed 
- [ ] Ask more people about speed-up via [sparse arrays](https://stackoverflow.com/questions/57315454/is-there-a-python-library-for-sparse-matrix-operations-for-non-standard-algebra)
- [ ] Test if further speed-up is possible by checking "is" instead of "==" for Zero-Morphisms (int vs numpy.int) (todo for Claudius)

## after version 1.0
- [ ] Unify BNComplexes and CobComplexes as instances of a common class Complex; field coefficients for Cob and conversion from BNAlgebra to Cob
- [ ] drawing immersed curves on R²
- [ ] tangle generation/simplification
- [ ] pairing
- [ ] deterministic arrow pushing algorithm/implementation of local systems
